service: serverless-node-users-api-v1

plugins:
  - serverless-plugin-optimize

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  
functions:
  get:
    handler: get.main
    events:
      - http:
          path: v1/users/{id}
          method: get
          cors: true
