service: users-api

plugins:
  # - serverless-bundle
  - serverless-plugin-optimize

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  
functions:
  get:
    handler: get.main
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
